version: '3.8'

services:
  chatserver:
    build:
      context: ./ChatServer
      dockerfile: Dockerfile
    ports:
      - "7891:7891"
    networks:
      - chat-network
    container_name: chatserver

  chatconsole:
    build:
      context: ./ChatConsole
      dockerfile: Dockerfile
    ports:
      - "7892:7891"  # Default first chatconsole port
    networks:
      - chat-network
    depends_on:
      - chatserver
    stdin_open: true
    tty: true
    environment:
      - USER_ID=${USER_ID}  # Use the dynamic USER_ID here
    restart: unless-stopped


networks:
  chat-network:
    driver: bridge
